

### Create task
POST https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task
Content-Type: application/json

{
  "title": "Projit finalni pripravu skoleni!!",
  "done": false,
  "owner": "Ales",
  "phone": "+420732286119",
  "duedate": "2023-08-02T15:27:00"
}

### Create task
PUT https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task/a24b85ff-738f-4426-850c-0cda932ae8b3
Content-Type: application/json

{
  "title": "get the fucking milk",
  "done": true,
  "owner": "Oldrich",
  "phone": "+420725423491",
  "duedate": "2023-08-12"
}

### delete task
DELETE https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task/50507ce3-d65f-4476-87e6-31438c781628

### get all tasks
GET https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task

### get all tasks by owner
GET https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task?owner=Pavel

### get one task
GET https://rlxx4p1xn5.execute-api.us-east-1.amazonaws.com/dev/task/f04cded4-266a-435a-a2aa-6cc46fa65a60
